config:
  MD001: false  # Header levels should only increment by one level at a time
  MD003: false  # Header style
  MD007: false  # Unordered list indentation
  MD013: false  # Line length
  MD033: false  # Allow inline HTML
  MD040: false  # Fenced code blocks should have a language specified
  MD041: false  # First line in file should be a top level header
  
globs:
  - "**/*.md"
  - "!node_modules/**"
  - "!.git/**"